gText_Birch_Welcome::
	.string "Hello Hello. Uhhhh\p"
	.string "Welcome to the world of POKéMON.\p"
	.string "My name is ITANI.\p"
	.string "But everyone calls me the TOK\n"
	.string "Teacher.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is a “POKéMON.” I think\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world has been edited by\n"
	.string "your friend known as OMAR.\p"
	.string "He's writing my text right now.\n"
	.string "This project has taken him a\l"
	.string "while to do so have fun.\p"
	.string "This is not the original game\n"
	.string "expect lots of changes.\p"
	.string "He wants me to tell you thanks\n"
	.string "for the time we had in School.\p"
	.string "Have fun with this\n"
	.string "it took him a while to make it.\p"
	.string "Wherever your journey takes,\n"
	.string "you I wish you good luck.\l"
	.string "Thanks again.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "What's your style?$"

gText_Birch_BoyOrGirl::
	.string "Are you masculine?\n"
	.string "Or feminine?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "town of LITTLEROOT.\l"
	.string "Understandable.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where many,\l"
	.string "things can happen and stuff!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
